### ISSUE TITLE
ERROR: Sorry, Copilot encountered an error.

### ISSUE THREAD

**Issue by StevenBucher98** [PowerShell/AIShell#303]
### Prerequisites

- [x] Write a descriptive title.
- [x] Make sure you are able to repro it on the latest version
- [x] Search the existing issues.

### Steps to reproduce

Randomly seem to hit an unknown error with Azure agent.

### Expected behavior

```console
To find the size of your VM in Azure, you can use the following Azure CLI command:

    az vm show --resource-group <resourceGroupName> --name <vmName> --query "hardwareProfile.vmSize"

  Placeholders:

  •  <resourceGroupName> : The name of your resource group.

  •  <vmName> : The name of your virtual machine.
```

### Actual behavior

```console
ERROR: Sorry, Copilot encountered an error.
Please try again or share your feedback.
ActivityId =
1emRekxQzRkEnZCy4C5smm-us|0000001,
Correlation ID =
1emRekxQzRkEnZCy4C5smm-us|0000001, Timestamp
= 2024-11-17T20:37:57.1765970Z
```

### Error details

```console
See above
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.4.6
PSEdition                      Core
GitCommitId                    7.4.6
OS                             Microsoft Windows 10.0.22631
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Version

1.0.0-preview1

### Visuals

![Image](https://github.com/user-attachments/assets/7081ab96-bf3d-46a1-93fd-b296948e8acc)

**Comment by khaliddermoumi** [comment]
I am getting exactly this error all the time.

Same version, az cli logged in, azure copilot running (via portal), installed manually following instructions

**Comment by daxian-dbw** [comment]
We need the Azure Copilot team to investigate the failure. Here are the exceptions retrieved from log based on the activity id `1emRekxQzRkEnZCy4C5smm-us|0000001`:

```
"exception": System.Net.Http.HttpRequestException: Response status code does not indicate success: 422 (Unprocessable Entity).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Microsoft.WindowsAzure.Copilot.Providers.HandlersDataProvider`1.GetData(String question, ITurnContext turnContext, CancellationToken cancellationToken, Boolean enableMSI) in /__w/1/s/src/roles/copilot/Providers/HandlersDataProvider.cs:line 143
   at Microsoft.WindowsAzure.Copilot.Providers.CLIDataProvider.GetCLIData(String question, ITurnContext turnContext, CancellationToken cancellationToken) in /__w/1/s/src/roles/copilot/Providers/CLIDataProvider.cs:line 47
   at Microsoft.WindowsAzure.Copilot.CLIHandler.OnMessageActivityAsync(ITurnContext`1 turnContext, CancellationToken cancellationToken) in /__w/1/s/src/roles/copilot/Handlers/CLIHandler.cs:line 80,
"message": CLIService.GetData threw an exception
```
```
"exception": System.ArgumentException: An item with the same key has already been added. Key: RecursiveTurn
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at Microsoft.WindowsAzure.Copilot.Orchestration.OrchestrationCommon.InvokeLocalServerHandlerAsync(ITurnContext turnContext, Activity activityForHandoff, ServerChatHandler serverHandler, ServerHandlerBase localServerHandler, CancellationToken cancellationToken) in /__w/1/s/src/roles/copilot/Orchestration/OrchestrationCommon.cs:line 500
   at Microsoft.WindowsAzure.Copilot.Orchestration.OrchestrationCommon.InvokeServerHandlerAsync(ITurnContext turnContext, Activity originalActivity, ServerChatHandler serverHandler, IChatReasoningResult chatReasoningResult, ChatHandlerContext context, CancellationToken cancellationToken) in /__w/1/s/src/roles/copilot/Orchestration/OrchestrationCommon.cs:line 273
   at Microsoft.WindowsAzure.Copilot.Orchestration.ClassifyOrchestrator.Orchestrate(ITurnContext`1 turnContext, IMessageActivity activity, CopilotConversationState conversationState, CancellationToken cancellationToken) in /__w/1/s/src/roles/copilot/Orchestration/ClassifyOrchestrator.cs:line 287
   at Microsoft.WindowsAzure.Copilot.CopilotBot.OnMessageActivityInternalAsync(ITurnContext`1 turnContext, IMessageActivity activity, CopilotConversationState conversationState, CancellationToken cancellationToken) in /__w/1/s/src/roles/copilot/Bots/CopilotBot.cs:line 530
   at Microsoft.WindowsAzure.Copilot.CopilotBot.OnMessageActivityAsync(ITurnContext`1 turnContext, CancellationToken cancellationToken) in /__w/1/s/src/roles/copilot/Bots/CopilotBot.cs:line 245
   at Microsoft.WindowsAzure.Copilot.CopilotBot.OnMessageActivityAsync(ITurnContext`1 turnContext, CancellationToken cancellationToken) in /__w/1/s/src/roles/copilot/Bots/CopilotBot.cs:line 256
   at Microsoft.Bot.Builder.ActivityHandler.OnTurnAsync(ITurnContext turnContext, CancellationToken cancellationToken)
   at Microsoft.WindowsAzure.Copilot.Orchestration.OrchestrationCommon.InvokeLocalServerHandlerAsync(ITurnContext turnContext, Activity activityForHandoff, ServerChatHandler serverHandler, ServerHandlerBase localServerHandler, CancellationToken cancellationToken) in /__w/1/s/src/roles/copilot/Orchestration/OrchestrationCommon.cs:line 505
   at Microsoft.WindowsAzure.Copilot.Orchestration.OrchestrationCommon.InvokeServerHandlerAsync(ITurnContext turnContext, Activity originalActivity, ServerChatHandler serverHandler, IChatReasoningResult chatReasoningResult, ChatHandlerContext context, CancellationToken cancellationToken) in /__w/1/s/src/roles/copilot/Orchestration/OrchestrationCommon.cs:line 273
   at Microsoft.WindowsAzure.Copilot.Orchestration.ClassifyOrchestrator.Orchestrate(ITurnContext`1 turnContext, IMessageActivity activity, CopilotConversationState conversationState, CancellationToken cancellationToken) in /__w/1/s/src/roles/copilot/Orchestration/ClassifyOrchestrator.cs:line 287
   at Microsoft.WindowsAzure.Copilot.CopilotBot.OnMessageActivityInternalAsync(ITurnContext`1 turnContext, IMessageActivity activity, CopilotConversationState conversationState, CancellationToken cancellationToken) in /__w/1/s/src/roles/copilot/Bots/CopilotBot.cs:line 530
   at Microsoft.WindowsAzure.Copilot.CopilotBot.OnMessageActivityAsync(ITurnContext`1 turnContext, CancellationToken cancellationToken) in /__w/1/s/src/roles/copilot/Bots/CopilotBot.cs:line 245
   at Microsoft.WindowsAzure.Copilot.CopilotBot.OnMessageActivityAsync(ITurnContext`1 turnContext, CancellationToken cancellationToken) in /__w/1/s/src/roles/copilot/Bots/CopilotBot.cs:line 256
   at Microsoft.Bot.Builder.ActivityHandler.OnTurnAsync(ITurnContext turnContext, CancellationToken cancellationToken)
   at Microsoft.WindowsAzure.Copilot.SaveConversationHistoryMiddleware.OnTurnAsync(ITurnContext turnContext, NextDelegate nextTurn, CancellationToken cancellationToken) in /__w/1/s/src/roles/copilot/Middleware/SaveConversationHistoryMiddleware.cs:line 108
   at Microsoft.WindowsAzure.Copilot.SaveConversationHistoryMiddleware.OnTurnAsync(ITurnContext turnContext, NextDelegate nextTurn, CancellationToken cancellationToken) in /__w/1/s/src/roles/copilot/Middleware/SaveConversationHistoryMiddleware.cs:line 121
   at Microsoft.WindowsAzure.Copilot.ResponseMetadataMiddleware.OnTurnAsync(ITurnContext turnContext, NextDelegate next, CancellationToken cancellationToken) in /__w/1/s/src/roles/copilot/Middleware/ResponseMetadataMiddleware.cs:line 29
   at Microsoft.Bot.Builder.MiddlewareSet.ReceiveActivityWithStatusAsync(ITurnContext turnContext, BotCallbackHandler callback, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.BotAdapter.RunPipelineAsync(ITurnContext turnContext, BotCallbackHandler callback, CancellationToken cancellationToken),
"message": Unhandled error of type "UnexpectedError": An item with the same key has already been added. Key: RecursiveTurn
```

**Comment by daxian-dbw** [comment]
I have sent an email to our contact in the Azure Copilot team about this issue and asked them to investigate.
