### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by SteveWyntontje** [PowerShell/AIShell#312]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the latest version
- [X] Search the existing issues.

### Steps to reproduce

I runned ```invoke-Expression "& { $(Invoke-RestMethod 'https://aka.ms/install-aishell.ps1') }"``` and it said 
```Downloading AI Shell package 'AIShell-1.0.0-preview.1-win-x64.zip' ...```
```Extracting AI Shell to 'C:\Users\wynto\AppData\Local\Programs\AIShell' ...```
```Installing the PowerShell module 'AIShell' ...```
```Install-PSResource:```
```Line |```
``` 171 |          Install-PSResource -Name AIShell -Repository PSGallery -Prere …```
```     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~```
```     | Unable to successfully install package 'AIShell': 'Could not find file 'C:\Users\wynto\Documents\PowerShell\Modules\AIShell'.'```.   

### Expected behavior

```console
AI Shell to '$destination' ...
```Adding AI Shell app to the Path environment variable ...```
```Installing the PowerShell module 'AIShell' ...```
```Installation succeeded. To learn more about AI Shell please visit https://aka.ms/AIShell-Docs. To get started please run Start-AIShell to start AI Shell.```
```

### Actual behavior

```console
> invoke-Expression "& { $(Invoke-RestMethod 'https://aka.ms/install-aishell.ps1') }"
```Downloading AI Shell package 'AIShell-1.0.0-preview.1-win-x64.zip' ...```
```Extracting AI Shell to 'C:\Users\wynto\AppData\Local\Programs\AIShell' ...```
```Installing the PowerShell module 'AIShell' ...```
```Install-PSResource:```
```Line |```
``` 171 |          Install-PSResource -Name AIShell -Repository PSGallery -Prere …```
```     | Unable to successfully install package 'AIShell': 'Could not find file 'C:\Users\wynto\Documents\PowerShell\Modules\AIShell'.'```
```PS> ```
```

### Error details

```console
Type        : System.Management.Automation.ActionPreferenceStopException
ErrorRecord :
    Exception             :
        Type           : System.Management.Automation.PSInvalidOperationException
        ErrorRecord    :
            Exception             :
                Type    : System.Management.Automation.ParentContainsErrorRecordException
                Message : Unable to successfully install package 'AIShell': 'Could not find file 'C:\Users\wynto\Docume
nts\PowerShell\Modules\AIShell'.'
                HResult : -2146233087
            CategoryInfo          : InvalidOperation: (:) [], ParentContainsErrorRecordException
            FullyQualifiedErrorId : InvalidOperation
        Message        : Unable to successfully install package 'AIShell': 'Could not find file 'C:\Users\wynto\Documen
ts\PowerShell\Modules\AIShell'.'
        InnerException :
            Type       : System.IO.FileNotFoundException
            Message    : Could not find file 'C:\Users\wynto\Documents\PowerShell\Modules\AIShell'.
            FileName   : C:\Users\wynto\Documents\PowerShell\Modules\AIShell
            TargetSite :
                Name          : CreateDirectory
                DeclaringType : [System.IO.FileSystem]
                MemberType    : Method
                Module        : System.Private.CoreLib.dll
            Source     : System.Private.CoreLib
            HResult    : -2147024894
            StackTrace :
   at System.IO.FileSystem.CreateDirectory(String fullPath, Byte[] securityDescriptor)
   at System.IO.Directory.CreateDirectory(String path)
   at Microsoft.PowerShell.PSResourceGet.Cmdlets.InstallHelper.MoveFilesIntoInstallPath(PSResourceInfo pkgInfo, Boolean
 isModule, Boolean isLocalRepo, String dirNameVersion, String tempInstallPath, String installPath, String newVersion, S
tring moduleManifestVersion, String scriptPath)
   at Microsoft.PowerShell.PSResourceGet.Cmdlets.InstallHelper.TryMoveInstallContent(String tempInstallPath, ScopeType
scope, Hashtable packagesHash)
        HResult        : -2146233079
    TargetObject          : Microsoft.PowerShell.PSResourceGet.Cmdlets.InstallPSResource
    CategoryInfo          : InvalidOperation: (Microsoft.PowerShel…s.InstallPSResource:InstallPSResource) [Install-PSRe
source], PSInvalidOperationException
    FullyQualifiedErrorId : InstallPackageFailed,Microsoft.PowerShell.PSResourceGet.Cmdlets.InstallPSResource
    InvocationInfo        :
        MyCommand        : Install-PSResource
        ScriptLineNumber : 171
        OffsetInLine     : 9
        HistoryId        : 18
        Line             :         Install-PSResource -Name AIShell -Repository PSGallery -Prerelease -TrustRepository
-ErrorAction Stop -WarningAction SilentlyContinue

        Statement        : Install-PSResource -Name AIShell -Repository PSGallery -Prerelease -TrustRepository -ErrorAc
tion Stop -WarningAction SilentlyContinue
        PositionMessage  : At line:171 char:9
                           +         Install-PSResource -Name AIShell -Repository PSGallery -Prere …
                           +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        InvocationName   : Install-PSResource
        CommandOrigin    : Internal
    ScriptStackTrace      : at Install-AIShellModule, <No file>: line 171
                            at <ScriptBlock>, <No file>: line 205
                            at <ScriptBlock>, <No file>: line 1
                            at <ScriptBlock>, <No file>: line 1
    PipelineIterationInfo :
              0
              1
TargetSite  :
    Name          : Invoke
    DeclaringType : [System.Management.Automation.Runspaces.PipelineBase]
    MemberType    : Method
    Module        : System.Management.Automation.dll
Message     : The running command stopped because the preference variable "ErrorActionPreference" or common parameter i
s set to Stop: Unable to successfully install package 'AIShell': 'Could not find file 'C:\Users\wynto\Documents\PowerSh
ell\Modules\AIShell'.'
Data        : System.Collections.ListDictionaryInternal
Source      : System.Management.Automation
HResult     : -2146233087
StackTrace  :
   at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
   at Microsoft.PowerShell.Executor.ExecuteCommandHelper(Pipeline tempPipeline, Exception& exceptionThrown, ExecutionOp
tions options)
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.4.6
PSEdition                      Core
GitCommitId                    7.4.6
OS                             Microsoft Windows 10.0.22631
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Version

v7.6.4 of PowerShell and v1.0.0-preview.1 of AIShell

### Visuals

[AIShell Problem.zip](https://github.com/user-attachments/files/17970133/AIShell.Problem.zip)

**Comment by StevenBucher98** [comment]
@daxian-dbw any thoughts on this? Not sure I understand why the script is checking for the location and then failing? It should recognize it is installed or partially installed and then prompt.

**Comment by daxian-dbw** [comment]
The error "Could not find file 'C:\Users\wynto\Documents\PowerShell\Modules\AIShell" was thrown by `Install-PSResource` when it tried to create the directory with that path. The stack trace is:
```
   at System.IO.FileSystem.CreateDirectory(String fullPath, Byte[] securityDescriptor)
   at System.IO.Directory.CreateDirectory(String path)
   at Microsoft.PowerShell.PSResourceGet.Cmdlets.InstallHelper.MoveFilesIntoInstallPath(PSResourceInfo pkgInfo, Boolean
 isModule, Boolean isLocalRepo, String dirNameVersion, String tempInstallPath, String installPath, String newVersion, S
tring moduleManifestVersion, String scriptPath)
```
I did some searches and find this is likely caused by Windows Defender treating the folder `C:\Users\wynto\Documents` as a protected folder. It can be worked around by excluding your app (pwsh in this case) by name. On Windows 11, see `Settings > Virus & threat protection > Virus & threat protection settings > Exclusions`, the settings may be at a different location on Windows 10, but should be somewhere similar.

This is my setting for `Exclusions`:
![image](https://github.com/user-attachments/assets/546e1c20-4033-4b16-9938-b213c7b3424f)

Here are the references from online search:
- https://github.com/dotnet/runtime/issues/24783#issuecomment-367780149
- https://stackoverflow.com/a/61739743
