### ISSUE TITLE
ERROR: Agent failed to generate a response: Project `proj_hidden` does not have access to model `gpt-4o`

### ISSUE THREAD

**Issue by HarryAdney** [PowerShell/AIShell#323]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the latest version
- [X] Search the existing issues.

### Steps to reproduce

Recently installed and run /agent config which opened openai.agent.json in VSCode.
Deleted comments and added a new API key generated on Openai.com for this purpose.
Config screen attached
![screenshot-aishell-config](https://github.com/user-attachments/assets/17508223-0022-41d0-8540-491a0dd0066d)
In AIShell selected ps-gpt4o as active model
Entered the text "what can you do?"

### Expected behavior

```console
A description of the AI's abilities be returned
```

### Actual behavior

```console
ERROR: Agent failed to generate a response: Project
`proj_itsE4CpnVVyXqV4V5wwoBcwI` does not have access to model `gpt-4o`
Status: 403 (Forbidden)
ErrorCode: model_not_found

Content:
{
    "error": {
        "message": "Project `proj_xXXXXxxxXXXxxxxXX` does not have access
to model `gpt-4o`",
        "type": "invalid_request_error",
        "param": null,
        "code": "model_not_found"
    }
}


Headers:
Date: Sat, 28 Dec 2024 13:11:05 GMT
Connection: keep-alive
Vary: REDACTED
X-Request-ID: REDACTED
Strict-Transport-Security: REDACTED
CF-Cache-Status: REDACTED
Set-Cookie: REDACTED
X-Content-Type-Options: REDACTED
Server: cloudflare
CF-RAY: REDACTED
Alt-Svc: REDACTED
Content-Type: application/json; charset=utf-8
Content-Length: 224

   at Azure.Core.HttpPipelineExtensions.ProcessMessageAsync(HttpPipeline
pipeline, HttpMessage message, RequestContext requestContext, CancellationToken
cancellationToken)
   at
Azure.AI.OpenAI.OpenAIClient.GetChatCompletionsStreamingAsync(ChatCompletionsOpti
ons chatCompletionsOptions, CancellationToken cancellationToken)
   at AIShell.OpenAI.Agent.ChatService.GetStreamingChatResponseAsync(String
input, CancellationToken cancellationToken)
   at
Spectre.Console.Status.<>c__DisplayClass17_0`1.<<StartAsync>b__0>d.MoveNext() in
/_/src/Spectre.Console/Live/Status/Status.cs:line 120
--- End of stack trace from previous location ---
   at
Spectre.Console.Progress.<>c__DisplayClass28_0`1.<<StartAsync>b__0>d.MoveNext()
in /_/src/Spectre.Console/Live/Progress/Progress.cs:line 133
--- End of stack trace from previous location ---
   at Spectre.Console.Internal.DefaultExclusivityMode.RunAsync[T](Func`1 func) in
/_/src/Spectre.Console/Internal/DefaultExclusivityMode.cs:line 40
   at Spectre.Console.Progress.StartAsync[T](Func`2 action) in
/_/src/Spectre.Console/Live/Progress/Progress.cs:line 116
   at Spectre.Console.Status.StartAsync[T](String status, Func`2 func) in
/_/src/Spectre.Console/Live/Status/Status.cs:line 117
   at AIShell.Kernel.Host.RunWithSpinnerAsync[T](Func`1 func, String status,
Nullable`1 spinnerKind)
   at AIShell.OpenAI.Agent.OpenAIAgent.ChatAsync(String input, IShell shell)
   at AIShell.Kernel.Shell.RunREPLAsync()

@openai-gpt>
```

### Error details

```console
"Project `proj_xXXXXxxxXXXxxxxXX` looked like an actual id, but I've no idea where that comes from.
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.4.6
PSEdition                      Core
GitCommitId                    7.4.6
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Version

1.0.0-preview.1

**Comment by StevenBucher98** [comment]
Thanks for the issue @HarryAdney! Are you paying for the plus version of chatGPT ($20/month?), it seems to work for me with this configuration on my account that is the plus version. The online docs say that access to GPT-4o is limited in the free version so that may restrict API calls.

**Comment by HarryAdney** [comment]
> Thanks for the issue @HarryAdney! Are you paying for the plus version of chatGPT ($20/month?), it seems to work for me with this configuration on my account that is the plus version. The online docs say that access to GPT-4o is limited in the free version so that may restrict API calls.

Thanks Steven, I'm using a free plan on that particular machine, so that's probably the answer. I'm still confused about the project id though ¯\_(ツ)_/¯

**Comment by StevenBucher98** [comment]
I suspect the project ID is likely some GUID the client uses to communicate with the openAI server side
